backend implementation and frontend logic
ProgramEquity/amplify pull request #243
Opened 2022-06-29 18:44 UTC by mariah622

Have reps be filterable by jurisdiction: federal, state, county

Tasks:

Create buttons in campaign.vue view
Have button filter by representative [levels](https://developers.google.com/civic-information/docs/v2/representatives/representativeInfoByAddress)
a. country = federal
b. level 1 = state
c. level 2 = county
Only show representative array that corresponds

Filter is working, however, some information is being omitted for some reason. I believe it's a stemming from the backend api that was implemented but I am unsure.

2022-06-29 19:19 UTC, gdomingu commented on src/components/SearchReps.vue
> +                                v-on:click="FilterList('administrativeArea1')"
Should this be `administrativeArea2`

2022-06-29 19:23 UTC, paramsiddharth commented on src/components/SearchReps.vue
> +                                v-on:click="FilterList('administrativeArea1')"
@gdomingu Yes, I agree.

2022-08-03 22:05 UTC, JamesMGreene requested changes
There are a handful of changes I'd like to see here before merging this. If I get a chance tonight, I will try to offer up a second PR building on your changes to help clarify/implement some of these suggestions.

2022-08-04 04:21 UTC, JamesMGreene commented
Here's a new PR that extends this one but addresses my PR Review feedback (mostly to reduce the overall number of changes needed now and future-proof the frontend a bit):
- https://github.com/ProgramEquity/amplify/pull/283

Please give that a review if you get a chance. 🙏🏻 👀

2022-08-08 19:17 UTC, closed without merging