Add the cats gif on pr push workflow
ProgramEquity/amplify pull request #346
Opened 2022-10-12 19:42 UTC by Lehcar

Co-authored-by: Manisha Priyadarshini <manishapriya94@github.com>

## Description

This adds the [action-cats workflow](https://github.com/ruairidhwm/action-cats) to the amplify repo.

2022-10-12 19:50 UTC, paramsiddharth commented on .github/workflows/cats.yml
> +      run: echo "Hello World"
```suggestion
      - name: Print "Hello World"
        run: echo "Hello World"
```

2022-10-12 19:50 UTC, paramsiddharth requested changes
Hi @Lehcar ! I think this might be an issue with the workflow preventing it from running.

2022-10-12 19:53 UTC, Lehcar commented
I'm going to close and reopen this PR to try and trigger the workflow (instead of adding the workflow_dispatch)

2022-10-12 19:54 UTC, Lehcar commented
Ok, this might be an issue with permissions, going to debug a bit

2022-10-12 19:58 UTC, paramsiddharth commented
@Lehcar I think reopening the PR might not trigger the workflow yet, just because the workflow isn't merged into `main`? So I think we can continue relying on `workflow_dispatch` and try to debug the workflow till then. :)

2022-10-12 20:24 UTC, Lehcar commented
> 

the actions UI isn't recognizing the action even with the workflow_dispatch trigger set. 
I'm not sure why, it should be appearing there 😕

2022-10-12 20:57 UTC, Lehcar commented
going to try and trigger this action by closing and opening? :?

2022-10-12 21:05 UTC, Lehcar commented
So we think the problem was that the Check formatting check was failing, causing the action to exit before it could pickup this workflow file. 

I pushed up a commit with the workflow_dispatch trigger on and with that check passing and the action ran (it did fail because it couldn't find the PR): https://github.com/ProgramEquity/amplify/actions/runs/3237828415

This _should_ work, but it can't really be tested until it's merged

2022-10-13 10:13 UTC, paramsiddharth commented
> So we think the problem was that the Check formatting check was failing, causing the action to exit before it could pickup this workflow file.
> 
> I pushed up a commit with the workflow_dispatch trigger on and with that check passing and the action ran (it did fail because it couldn't find the PR): https://github.com/ProgramEquity/amplify/actions/runs/3237828415
> 
> This _should_ work, but it can't really be tested until it's merged

Hmmm... @manishapriya94 What do you think? Should we go ahead and merge it to test it further?

2022-10-13 13:30 UTC, merged