Added Table of Contents
ProgramEquity/amplify pull request #358
Opened 2022-10-13 21:54 UTC by LoopFruits

Easy for users to navigate to different sections.

Documentation only PR, no builds affected

2022-10-14 05:50 UTC, paramsiddharth commented on README.md
> +
```suggestion
```

2022-10-14 05:52 UTC, paramsiddharth requested changes
There are some minor changes needed for consistency. The rest looks good!

2022-10-14 05:52 UTC, paramsiddharth commented on README.md
> +==================
```suggestion
## Table of Contents
```

2022-10-14 05:52 UTC, paramsiddharth commented on README.md
> +
```suggestion
```

2022-10-14 20:16 UTC, paramsiddharth approved these changes

2022-10-20 15:51 UTC, JimmyJammer commented
FWIW, GitHub automatically generates a Table of Contents for these if you just click on the upper-left menu button near the filename in the viewing panel:

<img width="432" alt="Screen Shot 2022-10-20 at 10 47 41 AM" src="https://user-images.githubusercontent.com/83616204/196997033-74a641c0-70a9-4ff0-9c56-5ec1616a872b.png">

The beauty of GitHub's automatic solution is that it will never become out-of-date. ✨ 

With that in mind, do we still want to add this? It is undoubtedly more visible, so it's just a question of if that visibility outweighs the long-term maintenance burden. 🤷‍♂️ 🤔

2022-10-20 16:56 UTC, paramsiddharth commented
> @JimmyJammer FWIW, GitHub automatically generates a Table of Contents for these if you just click on the upper-left menu button near the filename in the viewing panel:
> 
> <img alt="Screen Shot 2022-10-20 at 10 47 41 AM" width="432" src="https://user-images.githubusercontent.com/83616204/196997033-74a641c0-70a9-4ff0-9c56-5ec1616a872b.png">
> 
> The beauty of GitHub's automatic solution is that it will never become out-of-date. ✨
> 
> With that in mind, do we still want to add this? It is undoubtedly more visible, so it's just a question of if that visibility outweighs the long-term maintenance burden. 🤷‍♂️ 🤔

Good point! As amazing as this feature is, I think we'd still go with considering this PR for this particular repository. "More visibility" isn't exactly going to be the criterion, but I think the design team intended on having this added to the README.

Nevertheless, thank you for pointing out the fact that there's a button that automatically generates the ToC for us! It will now be helpful for me every time I navigate through GitHub repositories. 🤗

2022-10-20 16:57 UTC, JamesMGreene commented
Forgot I was logged into my test account there. 😊

2022-10-20 16:58 UTC, merged

2022-10-20 17:58 UTC, paramsiddharth commented
> Forgot I was logged into my test account there. 😊

@JamesMGreene Haha, big reveal, James! 😁 Your test account just got a new follower~! Had I known it was you, I'll probably let you make the final decision instead of what was proposed in the bugbash. Sorry about that!

2022-10-20 18:24 UTC, JamesMGreene commented
I'm fine with the change! 👍🏻