Added A Project Description
ProgramEquity/amplify pull request #493
Opened 2023-02-13 23:29 UTC by Alex-is-Gonzalez

-Added description to the top of the file to explain what Amplify does. 
 -Added a description to the video for the first video to clarify the purpose

2023-02-14 15:46 UTC, paramsiddharth commented on README.md
> + Amplify is an open-source app created for users to take the initiative in being part of an actionable step in the efforts to protect against climate change. The user is able to choose a climate camp
```suggestion
Amplify is an open-source app created for users to take the initiative in being part of an actionable step in the efforts to protect against climate change. The user is able to choose a climate campaign, then using their zip code, they will be able to select a representative of their choice. The user then donates to have their letter sent out by Amplify.
```

2023-02-14 15:49 UTC, paramsiddharth commented on README.md
> +<figcaption align = "center"><b>Codespaces Set Up</b></figcaption>
I don't think centring works here in GitHub's Markdown (check the preview), so you can get rid of the `figcaption` tag.

```suggestion
<b>Codespaces Set Up</b>
```

2023-02-14 15:50 UTC, paramsiddharth requested changes
.

2023-02-17 16:25 UTC, paramsiddharth approved these changes
Looks good to me! Well done, Alex. 🌼

2023-02-17 21:10 UTC, Alex-is-Gonzalez commented
Thank you for your guidance, Param!

2023-02-18 06:22 UTC, merged