Created welcome Message yml
ProgramEquity/amplify pull request #520
Opened 2023-03-02 22:48 UTC by Alex-is-Gonzalez

Created welcome message upon creating a first issue and first pr.

2023-03-06 14:47 UTC, paramsiddharth approved these changes
Looks good to me!

@JamesMGreene Do you think we'd be able to test this out using your second account, once merged?

2023-03-06 21:37 UTC, JamesMGreene reviewed
This workflow looks good overall, though I left a few suggestions for best practices.

I don't see anything here that would warrant the need to run it in a separate account first, so just make sure to keep an eye out for potential failing runs in the future. 👍🏻

2023-03-06 21:37 UTC, JamesMGreene commented on .github/workflows/welcome_message.yml
> +    steps:
I recommend adding [a `timeout-minutes` configuration](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) for **every** Actions job to ensure you don't end up wasting the default 6 hours in the case of a runaway Action/job:

```suggestion
    timeout-minutes: 2
    steps:
```

2023-03-06 21:37 UTC, JamesMGreene commented on .github/workflows/welcome_message.yml
> +
It's a best practice to restrict the permissions granted to the `GITHUB_TOKEN` to just the minimum set that are relevant to the workflow/job:

```suggestion

permissions:
  issues: write
  pull-requests: write

```

2023-03-06 21:37 UTC, JamesMGreene commented on .github/workflows/welcome_message.yml
> +        uses: garg3133/welcome-new-contributors@v1.2
From a security perspective, I would recommend you pin to a specific commit of the Action to ensure its tag (e.g. `v1.2`) is not maliciously swapped out from under you without giving you the opportunity to review it:

```suggestion
        uses: garg3133/welcome-new-contributors@a38583ed8282e23d63d7bf919ca2d9fb95300ca6
```

2023-03-08 08:21 UTC, paramsiddharth requested changes
@Alex-is-Gonzalez I think it's best we move forward with James's advice and update the workflow. :)

2023-03-15 18:34 UTC, Alex-is-Gonzalez commented
@JamesMGreene Thank you for the thorough feedback! I learned a lot from this, I went ahead and changed the yml based on the notes provided!

2023-03-19 14:42 UTC, JamesMGreene approved these changes
LGTM. Thanks for following up on my suggestions! ❤️

2023-03-19 14:45 UTC, merged