Markdown file detailing the Strip Checkout Implementation steps
ProgramEquity/amplify pull request #629
Opened 2023-10-24 20:32 UTC by EmaleeSoto

-Created Checkout markdown file to provide documenatation on the Stripe API and how it is used in Amplify
-File includes implementation steps for Stripe API end points

2023-10-29 15:24 UTC, DietBepis1 requested changes
This is pretty nice, but I think it would be better to add it into the Amplify wiki.

https://github.com/ProgramEquity/amplify/wiki

2023-12-10 03:49 UTC, Alex-is-Gonzalez reviewed
There is just a small Typo in the start of the MD file. Once that is changed, I will merge it

2023-12-10 03:49 UTC, Alex-is-Gonzalez commented on CHECKOUT.md
> +Amplify uses Stripe to process donations for non-profit organizations. Use these API endpoints to store and complete transactions.
Amplify uses Stripe to process donations for non-profit organizations.  Amplify uses these API endpoints to store and complete transactions.

2023-12-11 20:04 UTC, Alex-is-Gonzalez approved these changes
Thank you for creating the checkout.md

2023-12-11 20:15 UTC, merged