Create new v1 Campaign PUT Rest Endpoint
ProgramEquity/amplify pull request #701
Opened 2023-11-06 01:27 UTC by shangguanwang

## Description
Create new Rest endpoint for **PUT** `/v1/campaigns/:id`; Updates the specified campaign when given a JSON payload of modified fields

## Acceptance Criteria
- [x] The PUT endpoint should work properly to update a specific campaign when given a JSON payload of modified fields
- [ ] Testing script work as expected

## Related Issue
#615 

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Testing Steps / QA Criteria
- From your terminal, pull down this branch with `git pull origin 615-api-create-campaign-put-endpoint-Shangguan` and check that branch out with `git checkout 615-api-create-campaign-put-endpoint-Shangguan`
- Run `npm run dev` to launch the app
**Scenario 1**: Successfully update a campaign
In Postman, first GET `http://localhost:8080/api/v1/campaigns/5`, you should see the following result:
![original campaign 5 data](https://github.com/ProgramEquity/amplify/assets/24996005/6e883f09-3914-482a-b18e-236343289345)
Create a new PUT request, and input updated campaign JSON under "Body", expect to see a status 200 with the updated campaign as returned result
![success put request](https://github.com/ProgramEquity/amplify/assets/24996005/9544126c-205a-4761-aa03-ef2d1414acba)

**Scenario 2**: The Campaign URL is incorrect
In Postman, PUT `http://localhost:8080/api/v1/campaigns/10` as an example, expect to see a `404 not found` error
![campaign not found](https://github.com/ProgramEquity/amplify/assets/24996005/4316e57b-3b80-48d0-9346-7273a9140f3a)

2023-11-28 03:07 UTC, DietBepis1 requested changes
Good effort! Just a little cleanup and rebasing is needed.

2023-11-28 03:07 UTC, DietBepis1 commented on server/middleware/example.js
> +function exampleMiddleware(req, res, next) {
No need to keep the examples 🙂

2023-11-28 03:07 UTC, DietBepis1 commented on server/routes/api/v1/campaigns/index.js
> +// PUT request to update a campaign
Looks good!

2023-11-28 03:07 UTC, DietBepis1 commented on server/routes/api/v1/campaigns/index.js
> +router.get('/:id', async (req, res) => {
You can get rid of these examples also.

2023-11-28 03:46 UTC, shangguanwang commented
> Good effort! Just a little cleanup and rebasing is needed.

Thank you Glenn @DietBepis1 ! I've did the rebase and cleaned up the example code, let me know if there are anything else you want me to change before merge

2023-12-31 16:35 UTC, DietBepis1 approved these changes

2023-12-31 16:35 UTC, merged